#!/bin/bash

AUTO_GENERATE_COMMENT="/* DON'T EDIT THIS FILE, IT IS GENERATED BY generate-menuicons.sh */"

icon_dir=$(realpath "`dirname \"${BASH_SOURCE[0]}\"`/../src/assets/icons")

# 生成图标tsx文件名
normalized_iconname() {
  local input_string=$1

  # 进行非字母转换
  if [[ ! "$input_string" =~ ^[a-zA-Z] ]];then
    input_string="A${input_string}"
  else
    input_string=$(echo "$input_string" | sed -E 's/_(\w)/\U\1/g')
    input_string="${input_string^}"
  fi

  # 转首字母大写
  echo -n "$input_string"
}

make_package_svg_icon(){

  local package=${1:?}
  local size=${2:?}
  echo "make package icon: $package, size: $size"
  # 清理生成的文件
  rm -rfv "$icon_dir/${package}/index.tsx"
  rm -rfv "$icon_dir/${package}/icons/*"

  # index.tsx 文件内容
  local tsxfile="${AUTO_GENERATE_COMMENT}
"
  for icon_name in `ls $icon_dir/${package}/svg/*.svg | grep -v @ | awk -F/ '{print $NF}' | cut -d. -f1`;do
    # 追加 tsx 文件内容
    local iconname=$(normalized_iconname $icon_name)
    tsxfile="$tsxfile
export * from './icons/${iconname}';"

    cat <<EOF > "$icon_dir/${package}/icons/${iconname}.tsx"
${AUTO_GENERATE_COMMENT}

import clsx from 'clsx';
import React, { ImgHTMLAttributes, forwardRef, createContext } from 'react';

import ${iconname}_src from '../svg/$icon_name.svg';

interface AudpIconProps extends ImgHTMLAttributes<HTMLImageElement> {
  src?: string;
  className?: string;
  size?: 16 | 24 | 32;
  onClick?: React.MouseEventHandler<HTMLSpanElement>;
}

interface IconContextProps {
  prefixCls?: string;
  rootClassName?: string;
}

const IconContext = createContext<IconContextProps>({});

// TODO 待修返回正类型
const ${iconname}Icon: any = forwardRef(({size = $size, className, ...props}: AudpIconProps, ref: any) => {

  const { rootClassName } = React.useContext(IconContext);

  const classString = clsx(
    rootClassName,
    'audpicon',
    'audpicon-${icon_name}',
    className,
  );

  return (
    <img
      ref={ref}
      className={classString}
      src={${iconname}_src}
      alt="${iconname}"
      width={size}
      height={size}
      {...props}
    />
  );
});

export { ${iconname}_src, ${iconname}Icon };
EOF
  done

  # 生成 index 文件
  echo "$tsxfile" > "${icon_dir}/${package}/index.tsx"
}

case "$1" in
  menu)
    make_package_svg_icon $1 16
    ;;
  filecate)
    make_package_svg_icon $1 24
    ;;
  *)
    make_package_svg_icon filecate 24 || exit $?
    ;;
esac
