name: Build And Deploy WebUI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build And Deploy WebUI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Lint CSS
        run: pnpm lint:css

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test:run

      - name: Build Project
        run: pnpm run build

      - name: 检查编译结果
        run: ls -lhR ./dist
